locale: "en-US"
title: TnV Blog # Title of your site
url: 'https://trvinh.github.io' # the base hostname & protocol for your site
baseurl: "" # the subpath of your site, e.g. /blog/
google_analytics_key: UA-97697810-1
#permalink: /blog/:year/:month/:day/:title
#excerpt_separator: <!--more-->

# Default description in social shares for the jekyll-seo-tag gem
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.

# Author details for the jekyll-seo-tag gem
author:
  name: Vinh Tran
  email: trvinh@gmail.com

# Social details for the jekyll-seo-tag gem
social:
  name: TnV Blog
  links:
    - https://trvinh.github.io

permalink: pretty

gems:
  - "jekyll-feed"
  - "jekyll-seo-tag"
  - "jekyll-paginate"
  - "jekyll-sitemap"

# Jekyll SEO Tag
webmaster_verifications:
  google: # 1234
  bing: # 1234
  alexa: # 1234
  yandex: # 1234

# -----------
# CloudCannon

social_icons:
  - Facebook
  - Google Plus
  - Instagram
  - LinkedIn
  - Pinterest
  - Tumblr
  - Twitter
  - YouTube
  - RSS
